services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse
    ports: ["5432:5432"]
    volumes: ["pulse_pg:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: pulse
      MINIO_ROOT_PASSWORD: pulsepassword
    ports: ["9000:9000","9001:9001"]
    volumes: ["pulse_minio:/data"]
volumes:
  pulse_pg:
  pulse_minio:
